spring:
  h2:
    console:
      enabled: true

  graphql:
    graphiql:
      enable: true
      # graphiql? true? ??? ?? localhost:8080/h2-console? ?? localhost:8080/graphiql ??
      # graphql ??? ???? ?????.
      # ? ?? ??? IntelliJ? GraphQL ????? ???? IntelliJ?? ?? ???? ???? Postman??? ?????.
      printer:
        enable: true
      # ? ?? ? jpa? show-sql ?? graphql ??? ??? ???.

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true